name: Astro - S3 Deploy

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-deploy:
    environment: PRD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 sync ./dist s3://${{ vars.AWS_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront cache
        if: ${{ vars.AWS_CLOUDFRONT_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.AWS_CLOUDFRONT_DIST_ID }} \
            --paths "/*"

